<?php

namespace Igesef\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsOfTheDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsOfTheDayRepository extends EntityRepository
{
}
